-- Review and back up your existing Supabase database before running.
-- No sample or dummy data is inserted by this script.
create extension if not exists pgcrypto;
create table if not exists public.businesses(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now());
create table if not exists public.business_members(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null default 'member' check(role in('owner','admin','member')),created_at timestamptz not null default now(),unique(business_id,user_id));
create table if not exists public.customers(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,full_name text not null,phone text not null,email text,address text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(id,business_id));
create table if not exists public.enquiries(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,customer_id uuid not null,event_type text not null default 'Other',event_date date,venue text,guest_count integer,budget numeric(12,2),source text,status text not null default 'new' check(status in('new','contacted','quoted','won','lost')),notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(id,business_id),constraint enquiries_customer_fk foreign key(customer_id,business_id) references public.customers(id,business_id));
create table if not exists public.events(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,customer_id uuid not null,event_name text not null,event_type text,event_date date not null,venue text,guest_count integer,budget numeric(12,2),status text not null default 'planned',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(id,business_id),constraint events_customer_fk foreign key(customer_id,business_id) references public.customers(id,business_id));
create table if not exists public.quotations(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,customer_id uuid not null,quotation_number text not null,quotation_date date not null default current_date,valid_until date,subtotal numeric(12,2) not null default 0,tax_amount numeric(12,2) not null default 0,total_amount numeric(12,2) not null default 0,status text not null default 'draft',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(id,business_id),unique(business_id,quotation_number),constraint quotations_customer_fk foreign key(customer_id,business_id) references public.customers(id,business_id));
create table if not exists public.quotation_items(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,quotation_id uuid not null,description text not null,quantity numeric(10,2) not null default 1,unit_price numeric(12,2) not null default 0,created_at timestamptz not null default now(),constraint quotation_items_quote_fk foreign key(quotation_id,business_id) references public.quotations(id,business_id) on delete cascade);
create table if not exists public.invoices(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,customer_id uuid not null,invoice_number text not null,invoice_date date not null default current_date,due_date date,subtotal numeric(12,2) not null default 0,tax_amount numeric(12,2) not null default 0,total_amount numeric(12,2) not null default 0,status text not null default 'draft',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(id,business_id),unique(business_id,invoice_number),constraint invoices_customer_fk foreign key(customer_id,business_id) references public.customers(id,business_id));
create table if not exists public.transactions(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,transaction_date date not null default current_date,transaction_type text not null check(transaction_type in('income','expense')),category text,amount numeric(12,2) not null check(amount>0),payment_method text,reference text,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.follow_ups(id uuid primary key default gen_random_uuid(),business_id uuid not null references public.businesses(id) on delete cascade,customer_id uuid not null,due_date date not null,channel text,status text not null default 'pending',notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),constraint followups_customer_fk foreign key(customer_id,business_id) references public.customers(id,business_id));
-- Ensure RLS is enabled. Keep existing policies under review rather than disabling RLS.
alter table public.businesses enable row level security;
alter table public.business_members enable row level security;
alter table public.customers enable row level security;
alter table public.enquiries enable row level security;
alter table public.events enable row level security;
alter table public.quotations enable row level security;
alter table public.quotation_items enable row level security;
alter table public.invoices enable row level security;
alter table public.transactions enable row level security;
alter table public.follow_ups enable row level security;
drop policy if exists uv_business_member_select on public.businesses;
create policy uv_business_member_select on public.businesses for select to authenticated using(exists(select 1 from public.business_members bm where bm.business_id=businesses.id and bm.user_id=auth.uid()));
drop policy if exists uv_member_self_select on public.business_members;
create policy uv_member_self_select on public.business_members for select to authenticated using(user_id=auth.uid());
do $$ declare t text; begin foreach t in array array['customers','enquiries','events','quotations','quotation_items','invoices','transactions','follow_ups'] loop execute format('drop policy if exists uv_eventz_workspace_member_access on public.%I',t); execute format('create policy uv_eventz_workspace_member_access on public.%I for all to authenticated using(exists(select 1 from public.business_members bm where bm.business_id=%I.business_id and bm.user_id=auth.uid())) with check(exists(select 1 from public.business_members bm where bm.business_id=%I.business_id and bm.user_id=auth.uid()))',t,t,t); end loop; end $$;
grant select on public.businesses,public.business_members to authenticated;
grant select,insert,update,delete on public.customers,public.enquiries,public.events,public.quotations,public.quotation_items,public.invoices,public.transactions,public.follow_ups to authenticated;
